name: healthcare_marts
version: "1.2.0"
config-version: 2
profile: healthcare_marts
model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  healthcare_marts:
    staging:
      +materialized: view
    marts:
      +materialized: table
    audit:
      +materialized: table
